spring.application.name=fuel

# Database
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# Mail (Mailpit)
spring.mail.host=${MAIL_HOST:localhost}
spring.mail.port=${MAIL_PORT:1025}
spring.mail.username=any
spring.mail.password=any
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.ssl.enable=false

app.mail.from-email-address=noreply@fuel.local
app.mail.verification-subject= Verify your email address

#jwt
jwt.secret=${JWT_SECRET}
jwt.access-token-expiry-seconds=900
jwt.refresh-token-expiry-seconds=2592000

#redis rate-limiting
app.rate-limit.resend-verification.max-requests=3
app.rate-limit.resend-verification.window=1h